name: morphingdrones
channels:
  - conda-forge
  - robostack-staging
dependencies:
  - python=3.9.18
  - gitpython=3.1.30
  - pandas=1.5.2
  - casadi=3.6.2
  - adam-robotics=0.0.8
  - matplotlib=3.6.3
  - seaborn=0.12.2
  - numpy=1.23.5
  - scipy=1.10.0
  - scikit-learn=1.2.1
  - toml=0.10.2
  - rospkg=1.4.0
  - catkin_pkg=0.5.2
  - deap=1.3.3
  - pygad=2.19.1
  - black=23.12.1
  - ros-noetic-desktop-full=1.5.0
  - ros-noetic-jsk-rviz-plugins=2.1.8
  - pip:
      - liecasadi==0.0.6
      - odio_urdf@git+https://github.com/hauptmech/odio_urdf.git@8039543c5d4d66182f242313402ae84e38a5c8ea
